(progn
  (format t "~%~%")
  (format t "******************************************************************~%")
  (format t "*                 Welcome to Open Genera 2.0                     *~%")
  (format t "*                                                                *~%")
  (format t "*     This pre-defined world is a useful starting point for      *~%")
  (format t "*     exploring Genera. The default site name is 'Docker'.       *~%")
  (format t "*                                                                *~%")
  (format t "*     For documentation, type '<F1> D'                           *~%")
  (format t "*                                                                *~%")
  (format t "*     To get back to Lisp, type '<F1> L'                         *~%")
  (format t "*                                                                *~%")
  (format t "*     (F1 maps to the <SELECT> key)                              *~%")
  (format t "******************************************************************~%")
  (format t "~%~%"))
